// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9xDbRtLGeY3Lu4ryBTIuj3fXz5Qnf1yw',
    appId: '1:115838068071:web:7c3a858559cc2884b2fbc2',
    messagingSenderId: '115838068071',
    projectId: 'my-bored-board',
    authDomain: 'my-bored-board.firebaseapp.com',
    storageBucket: 'my-bored-board.appspot.com',
    measurementId: 'G-76HP9C5ZTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8oJ_BeYO3j2K4TGcILj0Vz7eKLqx2PPQ',
    appId: '1:115838068071:android:5e80f7462922ced3b2fbc2',
    messagingSenderId: '115838068071',
    projectId: 'my-bored-board',
    storageBucket: 'my-bored-board.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3ZhpO8COz_DefAaa6_QGiEb2HISEVVk',
    appId: '1:115838068071:ios:84220046f09fdc5eb2fbc2',
    messagingSenderId: '115838068071',
    projectId: 'my-bored-board',
    storageBucket: 'my-bored-board.appspot.com',
    iosBundleId: 'com.example.boastingBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3ZhpO8COz_DefAaa6_QGiEb2HISEVVk',
    appId: '1:115838068071:ios:a1d0e89c6798aff0b2fbc2',
    messagingSenderId: '115838068071',
    projectId: 'my-bored-board',
    storageBucket: 'my-bored-board.appspot.com',
    iosBundleId: 'com.example.boastingBoard.RunnerTests',
  );
}
